
name: Pylint

on: [push]

jobs:
  build:
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint black

      - name: Format Python code with black
        run: |
          black --config pyproject.toml src scripts
              
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files 'src/**/*.py') --output=lint.txt || true

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
 
